version: "3.7"

volumes:
  tactical_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_PATH:-/opt/tacticalrmm}/tactical_data

  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_PATH:-/opt/tacticalrmm}/postgres_data

  mongo_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_PATH:-/opt/tacticalrmm}/mongo_data

  mesh_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_PATH:-/opt/tacticalrmm}/mesh_data

  redis_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ROOT_PATH:-/opt/tacticalrmm}/redis_data
